version: '3'

services:  
  mariadb:
    image: mariadb:10.7
    restart: always
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=phonebook
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306           
 
 